### PR TITLE
Revert "Document PyPi"

### PR DESCRIPTION
**Pull request by jpmckinney**
Reverts open-contracting/lib-cove-ocds#29

### CODE REVIEW

**Comment by rhiaro** [comment]
Can we have a small note about the release process and link to https://ocds-standard-development-handbook.readthedocs.io/en/latest/coding/index.html#release-process so new devs don't miss this step, and to remind old devs who might forget?

**Comment by jpmckinney** [comment]
We could… but we don't link to things like https://opendataservices.gitbook.io/developer-docs/code/code-python from every Python repo. If ODS devs more frequently consult that GitBook, perhaps the best approach is to link from there to https://ocds-standard-development-handbook.readthedocs.io/en/latest/coding/ ?

**Comment by jpmckinney** [comment]
Note: Python 3.5 is failing for some reason. I don't think we care about Python 3.5 support, so I'm just as happy to remove it from Travis.

**Comment by ghost** [comment]
Quick comment before meeting: This server is Ubuntu 16 which is Python 3.5 so we do need it. I'm also seeing failures in Python 3.6, and from a very quick look I don't think the failures I'm currently seeing are anything to do with Python version. (Am I seeing different failures to you, was it re-run?)

**Comment by jpmckinney** [comment]
Hmm, strange, one pair of builds fails on both versions , another passes on 3.6: https://travis-ci.org/open-contracting/lib-cove-ocds/builds/592667829?utm_source=github_status&utm_medium=notification

**Comment by rhiaro** [comment]
Linking to the OCDS developer docs would also help non-ODS developers who might get involved in future. Not wanting to update multiple copies of the same docs is fair enough, but surfacing the primary docs is as many place as possible surely can't hurt, and will help when different people discover/remember things in different ways, plus is a convenience even for those who already know where to look.

**Comment by jpmckinney** [comment]
Okay, let's put this in a CONTRIBUTING.md (which we can copy across all projects if we like). It's not material for the readme, since pushing to PyPi is for a *tiny* audience.

**Comment by ghost** [comment]
[lib-cove: Update docs to support PyPi publication](https://trello.com/c/B0PMUXqu/104-lib-cove-update-docs-to-support-pypi-publication)

**Comment by ghost** [comment]
Closing as this has been done in different pull request.

**Comment by jpmckinney** [comment]
Done in #34

**Pull request closed without merging**
